files:
  - source: /pages/*.*
    translation: /pages/%locale%/%original_file_name%
  - source: /pages/docs/*.*
    translation: /pages/%locale%/docs/%original_file_name%
  - source: /themes/navy/languages/en.yml
    translation: /themes/navy/languages/%locale%.yml
