files:
  - source: /pages/*.*
    translation: /pages/%language%/%original_file_name%
  - source: /pages/docs/*.*
    translation: /pages/%language%/docs/%original_file_name%
  - source: /themes/navy/languages/en.yml
    translation: /themes/navy/languages/%language%.yml
